#!/bin/bash
# =============================================================================
# Copilot CLI Pipeline Script — SOLUTION
# 
# This script demonstrates programmatic mode (-p) by building an automated
# project health report using Copilot as a scriptable AI tool.
#
# Usage: ./pipeline-script.sh
# =============================================================================

set -e

REPORT_FILE="project-report.md"
echo "# Project Health Report" > "$REPORT_FILE"
echo "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# --- Section 1: Git History Analysis ---
echo "## Git History Summary" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# SOLUTION 1: Summarize recent commits
copilot -p "Look at the last 10 git commits in this repository. Summarize them as a concise bullet list with the commit hash (short), author, and a one-line description of what changed. Format as Markdown bullet points." \
  --allow-tool='shell(git)' --silent >> "$REPORT_FILE"

echo "" >> "$REPORT_FILE"

# --- Section 2: Code Health Assessment ---
echo "## Code Health" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# SOLUTION 2: Analyze code organization
copilot -p "Count the lines of code per file type (e.g., .js, .md, .json, .sh) in this project directory, excluding node_modules and .git. Present as a Markdown table with columns: File Type, File Count, Total Lines. Then add a brief 2-3 sentence assessment of the code organization." \
  --allow-tool='shell(find:*),shell(wc:*),shell(cat:*)' --silent >> "$REPORT_FILE"

echo "" >> "$REPORT_FILE"

# --- Section 3: TODO Scanner ---
echo "## Open TODOs" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# SOLUTION 3: Find and categorize TODO comments
copilot -p "Search all source files in this project for TODO, FIXME, HACK, and XXX comments (excluding node_modules). List them as a numbered Markdown list, grouped by priority: FIXME first (critical), then TODO (normal), then HACK (technical debt), then XXX (needs attention). Include the filename and line number for each." \
  --allow-tool='shell(grep:*),shell(find:*)' --silent >> "$REPORT_FILE"

echo "" >> "$REPORT_FILE"

# --- Section 4: Dependency Check ---
echo "## Dependencies" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# SOLUTION 4: Analyze dependencies
copilot -p "Read the package.json file in this project. List all dependencies and devDependencies in a Markdown table with columns: Package, Version, Type (dependency/devDependency). If the version uses a caret (^) or tilde (~), note what range that allows." \
  --allow-tool='view' --silent >> "$REPORT_FILE"

echo "" >> "$REPORT_FILE"

# --- Final Summary ---
echo "---" >> "$REPORT_FILE"
echo "*Report generated by Copilot CLI pipeline script*" >> "$REPORT_FILE"

echo "✅ Report generated: $REPORT_FILE"
echo ""
cat "$REPORT_FILE"
