#!/bin/bash
# =============================================================================
# Copilot CLI Pipeline Script
# 
# This script demonstrates programmatic mode (-p) by building an automated
# project health report. Fill in the TODO sections with copilot commands.
#
# Usage: ./pipeline-script.sh
# =============================================================================

set -e

REPORT_FILE="project-report.md"
echo "# Project Health Report" > "$REPORT_FILE"
echo "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# --- Section 1: Git History Analysis ---
echo "## Git History Summary" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# TODO 1: Use copilot in programmatic mode to summarize the last 10 commits.
# Requirements:
#   - Use: copilot -p "..." --allow-tool='shell(git)' --silent
#   - Ask Copilot to summarize the last 10 commits in a concise bullet list
#   - Append the output to $REPORT_FILE
# 
# Your command here:
# copilot -p "___" --allow-tool='shell(git)' --silent >> "$REPORT_FILE"


echo "" >> "$REPORT_FILE"

# --- Section 2: Code Health Assessment ---
echo "## Code Health" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# TODO 2: Use copilot to analyze code quality.
# Requirements:
#   - Use programmatic mode with appropriate tool permissions
#   - Ask Copilot to count lines of code per file type in the project
#   - Include a brief assessment of code organization
#   - Append to $REPORT_FILE
#
# Your command here:
# copilot -p "___" --allow-tool='shell(find:*),shell(wc:*)' --silent >> "$REPORT_FILE"


echo "" >> "$REPORT_FILE"

# --- Section 3: TODO Scanner ---
echo "## Open TODOs" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# TODO 3: Use copilot to find and categorize TODO comments.
# Requirements:
#   - Use programmatic mode
#   - Ask Copilot to find all TODO, FIXME, HACK, and XXX comments in the project
#   - Categorize them by priority (FIXME > TODO > HACK > XXX)
#   - Format as a numbered list
#   - Append to $REPORT_FILE
#
# Your command here:
# copilot -p "___" --allow-tool='shell(grep:*),shell(find:*)' --silent >> "$REPORT_FILE"


echo "" >> "$REPORT_FILE"

# --- Section 4: Dependency Check ---
echo "## Dependencies" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# TODO 4: Use copilot to analyze package.json dependencies.
# Requirements:
#   - Read the package.json and list all dependencies with their versions
#   - Note any that might have newer major versions available
#   - Append to $REPORT_FILE
#
# Your command here:
# copilot -p "___" --allow-tool='view' --silent >> "$REPORT_FILE"


echo "" >> "$REPORT_FILE"

# --- Final Summary ---
echo "---" >> "$REPORT_FILE"
echo "*Report generated by Copilot CLI pipeline script*" >> "$REPORT_FILE"

echo "✅ Report generated: $REPORT_FILE"
echo ""
cat "$REPORT_FILE"
